# プロジェクト収支システム - 開発環境用 Docker Compose
version: '3.8'

services:
  # Flask アプリケーション (開発用)
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: project-revenue-web-dev
    restart: unless-stopped
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - SECRET_KEY=dev-secret-key
    volumes:
      - .:/app
      - ./data:/app/data
      - ./uploads:/app/uploads
    ports:
      - "5000:5000"
    networks:
      - app-network
    command: python app.py

  # Nginx (開発用 - オプション)
  nginx:
    image: nginx:alpine
    container_name: project-revenue-nginx-dev
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./static:/var/www/static:ro
    networks:
      - app-network
    depends_on:
      - web

networks:
  app-network:
    driver: bridge